#!/bin/bash
pw=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1)
{
    echo -e "$pw\n$pw" | lxc exec $1 -- passwd root
} &> /dev/null
echo "** New Root Password: $pw";
sudo chown root:root ${BASH_SOURCE%/*}/../configs/*;
lxc file push ${BASH_SOURCE%/*}/../configs/sshd_config $1/etc/ssh/ &&
lxc exec $1 -- service sshd restart
lxc file push ${BASH_SOURCE%/*}/../configs/sources.list $1/etc/apt/

